# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# build path: /home/duke/actions-runner/_work/iceni-driving-school/iceni-driving-school/Iceni.Admin/Server/bin/Debug/net7.0/publish/
name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --no-restore
    - name: Stop API
      run: pm2 stop ice-api
    - name: Copy API files
      run: cp -R /home/duke/github-runner/_work/iceni-driving-school/iceni-driving-school/Iceni.Api/bin/Debug/net7.0/publish/* /var/www/sites/api.icenidrivingschool.co.uk
    - name: Start API
      run: pm2 start ice-api
    - name: Stop Admin
      run: pm2 stop ice-admin
    - name: Copy Admin files
      run: cp -R /home/duke/github-runner/_work/iceni-driving-school/iceni-driving-school/Iceni.Admin/Server/bin/Debug/net7.0/publish/* /var/www/sites/admin.icenidrivingschool.co.uk
    - name: Start Admin
      run: pm2 start ice-admin
    